version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3.6
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    restart: always
    image: dental-clinic-smile
    command: yarn start
    volumes:
      - ./dist:/usr/src/dental-clinic-smile/dist
    ports:
      - "5050:5050"
    links: 
      - mongo